### ISSUE TITLE
Character will get stuck moving in a direction

### ISSUE THREAD

**Issue by simondevenish** [libtcod/treeburner#8]
Using WASD to move, sometimes the player will get stuck in a direction.

**Comment by HexDecimal** [comment]
Related to #3.  This is a bug in libtcod's event system combined with the engines general poor handling of events.  Specific events can be dropped due to the order the engine tries to fetch them.

I added [a workaround](https://github.com/libtcod/pyromancer/commit/dfa153398863cf5286afa6cd6a16b19922accc3a) to the Pyromancer code which checks SDL's keyboard state instead of taking libtcod events, but I want to fix all issues related to events rather than just one.  It can be cherry-picked into this codebase if you wanted a quick solution.
